/*
Copyright 2019 oneonestar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	prestocontrollerv1alpha1 "github.com/oneonestar/presto-controller/pkg/apis/prestocontroller/v1alpha1"
	versioned "github.com/oneonestar/presto-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/oneonestar/presto-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/oneonestar/presto-controller/pkg/client/listers/prestocontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PrestoInformer provides access to a shared informer and lister for
// Prestos.
type PrestoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PrestoLister
}

type prestoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPrestoInformer constructs a new informer for Presto type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPrestoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPrestoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPrestoInformer constructs a new informer for Presto type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPrestoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PrestocontrollerV1alpha1().Prestos(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PrestocontrollerV1alpha1().Prestos(namespace).Watch(options)
			},
		},
		&prestocontrollerv1alpha1.Presto{},
		resyncPeriod,
		indexers,
	)
}

func (f *prestoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPrestoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *prestoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&prestocontrollerv1alpha1.Presto{}, f.defaultInformer)
}

func (f *prestoInformer) Lister() v1alpha1.PrestoLister {
	return v1alpha1.NewPrestoLister(f.Informer().GetIndexer())
}
