/*
Copyright 2019 oneonestar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/oneonestar/presto-controller/pkg/apis/prestocontroller/v1alpha1"
	scheme "github.com/oneonestar/presto-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrestosGetter has a method to return a PrestoInterface.
// A group's client should implement this interface.
type PrestosGetter interface {
	Prestos(namespace string) PrestoInterface
}

// PrestoInterface has methods to work with Presto resources.
type PrestoInterface interface {
	Create(*v1alpha1.Presto) (*v1alpha1.Presto, error)
	Update(*v1alpha1.Presto) (*v1alpha1.Presto, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Presto, error)
	List(opts v1.ListOptions) (*v1alpha1.PrestoList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Presto, err error)
	PrestoExpansion
}

// prestos implements PrestoInterface
type prestos struct {
	client rest.Interface
	ns     string
}

// newPrestos returns a Prestos
func newPrestos(c *PrestocontrollerV1alpha1Client, namespace string) *prestos {
	return &prestos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the presto, and returns the corresponding presto object, and an error if there is any.
func (c *prestos) Get(name string, options v1.GetOptions) (result *v1alpha1.Presto, err error) {
	result = &v1alpha1.Presto{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prestos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Prestos that match those selectors.
func (c *prestos) List(opts v1.ListOptions) (result *v1alpha1.PrestoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PrestoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prestos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested prestos.
func (c *prestos) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("prestos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a presto and creates it.  Returns the server's representation of the presto, and an error, if there is any.
func (c *prestos) Create(presto *v1alpha1.Presto) (result *v1alpha1.Presto, err error) {
	result = &v1alpha1.Presto{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("prestos").
		Body(presto).
		Do().
		Into(result)
	return
}

// Update takes the representation of a presto and updates it. Returns the server's representation of the presto, and an error, if there is any.
func (c *prestos) Update(presto *v1alpha1.Presto) (result *v1alpha1.Presto, err error) {
	result = &v1alpha1.Presto{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prestos").
		Name(presto.Name).
		Body(presto).
		Do().
		Into(result)
	return
}

// Delete takes name of the presto and deletes it. Returns an error if one occurs.
func (c *prestos) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prestos").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *prestos) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prestos").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched presto.
func (c *prestos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Presto, err error) {
	result = &v1alpha1.Presto{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("prestos").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
