/*
Copyright 2019 oneonestar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	operatorv1alpha1 "github.com/oneonestar/presto-operator/pkg/apis/operator/v1alpha1"
	versioned "github.com/oneonestar/presto-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/oneonestar/presto-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/oneonestar/presto-operator/pkg/client/listers/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PrestoClusterInformer provides access to a shared informer and lister for
// PrestoClusters.
type PrestoClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PrestoClusterLister
}

type prestoClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPrestoClusterInformer constructs a new informer for PrestoCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPrestoClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPrestoClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPrestoClusterInformer constructs a new informer for PrestoCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPrestoClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().PrestoClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().PrestoClusters(namespace).Watch(options)
			},
		},
		&operatorv1alpha1.PrestoCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *prestoClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPrestoClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *prestoClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operatorv1alpha1.PrestoCluster{}, f.defaultInformer)
}

func (f *prestoClusterInformer) Lister() v1alpha1.PrestoClusterLister {
	return v1alpha1.NewPrestoClusterLister(f.Informer().GetIndexer())
}
