/*
Copyright 2019 oneonestar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/oneonestar/presto-operator/pkg/apis/operator/v1alpha1"
	scheme "github.com/oneonestar/presto-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrestoClustersGetter has a method to return a PrestoClusterInterface.
// A group's client should implement this interface.
type PrestoClustersGetter interface {
	PrestoClusters(namespace string) PrestoClusterInterface
}

// PrestoClusterInterface has methods to work with PrestoCluster resources.
type PrestoClusterInterface interface {
	Create(*v1alpha1.PrestoCluster) (*v1alpha1.PrestoCluster, error)
	Update(*v1alpha1.PrestoCluster) (*v1alpha1.PrestoCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PrestoCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.PrestoClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PrestoCluster, err error)
	PrestoClusterExpansion
}

// prestoClusters implements PrestoClusterInterface
type prestoClusters struct {
	client rest.Interface
	ns     string
}

// newPrestoClusters returns a PrestoClusters
func newPrestoClusters(c *OperatorV1alpha1Client, namespace string) *prestoClusters {
	return &prestoClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the prestoCluster, and returns the corresponding prestoCluster object, and an error if there is any.
func (c *prestoClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.PrestoCluster, err error) {
	result = &v1alpha1.PrestoCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prestoclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PrestoClusters that match those selectors.
func (c *prestoClusters) List(opts v1.ListOptions) (result *v1alpha1.PrestoClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PrestoClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prestoclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested prestoClusters.
func (c *prestoClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("prestoclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a prestoCluster and creates it.  Returns the server's representation of the prestoCluster, and an error, if there is any.
func (c *prestoClusters) Create(prestoCluster *v1alpha1.PrestoCluster) (result *v1alpha1.PrestoCluster, err error) {
	result = &v1alpha1.PrestoCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("prestoclusters").
		Body(prestoCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a prestoCluster and updates it. Returns the server's representation of the prestoCluster, and an error, if there is any.
func (c *prestoClusters) Update(prestoCluster *v1alpha1.PrestoCluster) (result *v1alpha1.PrestoCluster, err error) {
	result = &v1alpha1.PrestoCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prestoclusters").
		Name(prestoCluster.Name).
		Body(prestoCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the prestoCluster and deletes it. Returns an error if one occurs.
func (c *prestoClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prestoclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *prestoClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prestoclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched prestoCluster.
func (c *prestoClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PrestoCluster, err error) {
	result = &v1alpha1.PrestoCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("prestoclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
